name: Fast Forward Merge

on:
  workflow_call:
    inputs:
      target_branch:
        description: 'Target branch to fast-forward merge into - default is main'
        required: false
        type: string
        default: 'main'
      user_name:
        description: 'Git user name for the merge commit'
        required: true
        type: string
      user_email:
        description: 'Git user email for the merge commit'
        required: true
        type: string
    secrets:
      READY_PUSHER:
        description: 'GitHub token for CLI operations, needs write permissions for contents (deprecated - use token instead)'
        required: false
      token:
        description: 'GitHub token for CLI operations, needs write permissions for contents'
        required: false

jobs:
  ffmerge:
    name: Fast Forward Only
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:

    - name: Validate token availability
      run: |
        if [ -z "${{ secrets.token }}" ] && [ -z "${{ secrets.READY_PUSHER }}" ]; then
          echo "❌ Error: Either 'token' or 'READY_PUSHER' secret must be provided"
          echo "Please provide one of these secrets for authentication:"
          echo "  - token: GitHub token with write permissions (recommended)"
          echo "  - READY_PUSHER: GitHub token with write permissions (deprecated)"
          exit 1
        fi
        if [ -n "${{ secrets.token }}" ] && [ -n "${{ secrets.READY_PUSHER }}" ]; then
          echo "⚠️  Warning: Both 'token' and 'READY_PUSHER' secrets provided. Using 'token'."
        fi
        if [ -n "${{ secrets.token }}" ]; then
          echo "✅ Using 'token' secret for authentication"
        else
          echo "✅ Using 'READY_PUSHER' secret for authentication (consider migrating to 'token')"
        fi

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ inputs.target_branch }}
        token: ${{ secrets.token || secrets.READY_PUSHER }}

    - name: Set up git config
      run: |
        git config --global user.name "${{ inputs.user_name }}"
        git config --global user.email "${{ inputs.user_email }}"

    - name: Fast-Forward merge to target branch
      env:
        GH_TOKEN: ${{ secrets.token || secrets.READY_PUSHER }}

      run: |
        git checkout ${{ inputs.target_branch }}
        git merge --ff-only ${{ github.sha }}
        git push origin ${{ inputs.target_branch }}
        echo "Successfully fast-forward merged '${{ github.sha }}' into ${{ inputs.target_branch }}"  >> $GITHUB_STEP_SUMMARY

